/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import {
  EffectComposer,
  SelectiveBloom,
  Select,
} from '@react-three/postprocessing'
import StyleProps from '../../props/style.props'

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
  }
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
  }
}

export default function Model({
  className,
  ...props
}: JSX.IntrinsicElements['group'] & StyleProps) {
  const ref = useRef()

  const { nodes } = useGLTF('/retrowave-transformed.glb') as GLTFResult

  const sunRef = useRef()
  const lightRef = useRef()
  const mountainsRef = useRef()
  const groupRef = useRef()

  return (
    <>
      <group ref={groupRef} {...props} dispose={null}>
        <group
          name="Camera"
          ref={sunRef}
          position={[0, 0.54, -8]}
          rotation={[1.54, 0, Math.PI]}
        >
          <mesh
            geometry={nodes.Sphere.geometry}
            material-color="rgb(255, 138, 0)"
            position={[-0.02, -322.62, 9.55]}
            rotation={[1.54, 0, -Math.PI]}
            scale={[60, 60, 60]}
          />
        </group>
        <group scale={8}>
          <mesh
            geometry={nodes.Plane_1.geometry}
            material-color="rgb(23, 20, 29)"
          />
          <mesh
            ref={mountainsRef}
            geometry={nodes.Plane_2.geometry}
            material-color="rgb(229, 46, 113)"
          />
        </group>
      </group>
      <directionalLight
        color="#ffffff"
        intensity={0.25}
        position={[0, -1, 0]}
        ref={lightRef}
      />

      {lightRef.current && (
        <EffectComposer>
          <SelectiveBloom
            mipmapBlur
            lights={[lightRef]}
            selection={[sunRef, mountainsRef]}
            intensity={7}
            radius={0.75}
            selectionLayer={1}
            luminanceThreshold={0}
            luminanceSmoothing={1}
            height={1080}
            width={1920}
          />
        </EffectComposer>
      )}
    </>
  )
}

useGLTF.preload('/retrowave-transformed.glb')
